---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

# appservers:
#     hosts:
#       appserver-vm:
#         ansible_host: appserver
#       frontend-vm:
#         ansible_host: devopsvm2
#       gcloud-app-server:
#         ansible_host: devops-gcloud
docker-servers:
  hosts:
      dockervm:
          ansible_host: appserver

dbservers:
    hosts:
      dbserver-vm:
          ansible_host: dbserver
      azure-db-server:
          ansible_host: devopsvm

backendservers:
    hosts:
      backend-server:
        ansible_host: devops-gcloud

frontendservers:
    hosts:
      frontend-server:
          ansible_host: devopsvm2