app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:postgresql://dbserver:5432/appdb1
    VITE_BACKEND:  http://51.103.251.219
    
service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar target/demo-0.0.1-SNAPSHOT.jar"

