# appdir: "/home/it2021077/spring"
# branch: "api"
# appuser: "{{ansible_user_id}}"
# appgroup: "{{ansible_user_gid}}"
# app_port: 9090
# app:
#   env:
#     server.port: 9090
#     spring.datasource.username: appuser
#     spring.datasource.password: apppassword
#     spring.datasource.url: jdbc:postgresql://4.233.185.183:5432/appdb1

# service:
#   workingdir: "/home/it2021077/spring"
#   execstart: "java -jar target/demo-0.0.1-SNAPSHOT.jar"
appdir: "{{ ansible_user_dir }}/spring"
branch: "api"
appuser: "{{ ansible_user_id }}"
appgroup: "{{ ansible_user_gid }}"
app_port: 9090
app:
  env:
    server.port: "{{ app_port }}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:postgresql://4.233.185.183:5432/appdb1
    
service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar target/demo-0.0.1-SNAPSHOT.jar"